### ISSUE TITLE
Using the bridge along with OpenHAB running on Raspberry Pi

### ISSUE THREAD

**Issue by monajalal** [armzilla/amazon-echo-ha-bridge#63]
So I am running OpenHAB within Rasperry Pi and I saved the .jar file in my OS X and I run it within OS X terminal and I get the following error. Can you please let me know how I can fix that?
java -jar amazon-echo-bridge-0.2.1.jar –upnp.config.address=192.168.1.105
Exception in thread “main” java.lang.UnsupportedClassVersionError: com/armzilla/ha/SpringbootEntry : Unsupported major.minor version 52.0
at java.lang.ClassLoader.defineClass1(Native Method)
at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
at java.security.AccessController.doPrivileged(Native Method)
at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
at org.springframework.boot.loader.LaunchedURLClassLoader.doLoadClass(LaunchedURLClassLoader.java:163)
at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:136)
at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:46)
at java.lang.Thread.run(Thread.java:745)

**Comment by robwbartel** [comment]
The .jar was compiled with Java 8, but you're executing it under Java 7.

**Comment by arch1v1st** [comment]
@robwbartel - indeed.  I hit this too when setting up Amazon Echo HA Bridge.  Java JRE v1.8 seems to be required.
