### ISSUE TITLE
Using the bridge along with OpenHAB running on Raspberry Pi

### ISSUE THREAD

**Issue by monajalal** [armzilla/amazon-echo-ha-bridge#64]
I get the following error when I run the .jar in Raspberry Pi (starting with a sudo before java jar ...)
However even when running within Raspbian I get this error:

asticsearchAutoConfiguration : Closing Elasticsearch client
2016-01-24 23:07:58.279  INFO 2411 --- [           main] org.elasticsearch.node                   : [Bres] stopping ...
2016-01-24 23:07:58.336  INFO 2411 --- [           main] org.elasticsearch.node                   : [Bres] stopped
2016-01-24 23:07:58.337  INFO 2411 --- [           main] org.elasticsearch.node                   : [Bres] closing ...
2016-01-24 23:07:58.413  INFO 2411 --- [           main] org.elasticsearch.node                   : [Bres] closed
java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:53)
    at java.lang.Thread.run(Thread.java:744)
Caused by: java.lang.IllegalStateException: Tomcat connector in failed state
    at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer.start(TomcatEmbeddedServletContainer.java:157)
    at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.startEmbeddedServletContainer(EmbeddedWebApplicationContext.java:288)
    at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.finishRefresh(EmbeddedWebApplicationContext.java:141)
    at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:483)
    at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118)
    at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:686)
    at org.springframework.boot.SpringApplication.run(SpringApplication.java:320)
    at org.springframework.boot.SpringApplication.run(SpringApplication.java:957)
    at org.springframework.boot.SpringApplication.run(SpringApplication.java:946)
    at com.armzilla.ha.SpringbootEntry.main(SpringbootEntry.java:14)
    ... 6 more
pi@raspberrypi /opt/openhab/echo $

**Comment by sat5project** [comment]
I had similar errors but it turns out the initial (and most applicable) error had scrolled off my terminal history.  Be sure you've found the very first error to appear in the output.
